### ISSUE TITLE
I'd like to help by working on this project

### ISSUE THREAD

**Issue by szepeviktor** [hypnotox/abyss#1]
Hello!

I like top-down programming (starting with DX)
What would the user type in his editor while using abyss?

**Comment by hypnotox** [comment]
I'm actually currently in the process of rewriting the whole library since I dislike how it works right now. (The library isn't even tagged or anything, that was the first one off idea on an evening.)

It's awesome that you want to help out, but it will probably take a few days until i have my idea hashed out to how i want it to work and the base implementation for that.
I'll give you a heads up when that happened.

**Comment by szepeviktor** [comment]
Could you show me the usage in few lines?
What is the format of a schema? JSON, PHP array, 👉🏻YAML👈🏻  ...

**Comment by hypnotox** [comment]
The feature set i have in mind:
- It should have a `Schema` that 
  - has an array representation (this automatically makes it also compatible with JSON or YAML representations 😉)
- It should have a `SchemaBuilder` that
  - understands the structure of this array
  - can parse it into an "object tree" (i aim for a very object oriented approach with strong typing)
  - can traverse this object tree and edit it, add/edit/remove nodes, etc.
- It should have a `Validator` that
  - constructs with a schema object
  - has a `validate(array $array): ValidationResult{isValid: bool, errors: ValidationError[]}`

General coding approach:
- All classes should be backed by an interface and final
- All classes should be immutable

How does that sound to you?

**Comment by szepeviktor** [comment]
Very good!

Let me continue in the next issue.
